### ISSUE TITLE
FR: Google Wallet integration

### ISSUE THREAD

**Issue by AndyScherzinger** [AndlyticsProject/andlytics#316]
TaRSyS asked me if we would like to integrate Google Checkout in our app.

He gave me the implementation of his app which he will then discontinue:
https://play.google.com/store/apps/details?id=tarsys.mycheckout

If you are fine with this feature @nelenkov and @willlunniss I will open a new feature branch and start working on this in the upcoming weeks/month (no idea yet how long this will take :)

I already checked with him and he is fine with publishing his implementation (as part of Andlytics) under the Apache License.

**Comment by frmz** [comment]
Agree with @tomrozb i think a very useful and very easy to do addition would be to have total revenue based on the sum of the apps currently visible. Should i open a new ticket asking this or this one is moving ahead and will cover that as well?

**Comment by willlunniss** [comment]
Create a new one, also describe how you might want the data presented. However, all of the project maintainers are very busy at the moment, so your best bet is to create a PR with the feature.
