### ISSUE TITLE
"A network error has occurred. Please try again later"

### ISSUE THREAD

**Issue by emostar** [AndlyticsProject/andlytics#664]
Here is my logcat output:

````
D/DevConsoleV2(30189): Found 5 apps for 00844154241665121830
D/DevConsoleV2(30189): Incomplete packages: 0
D/DevConsoleV2(30189): Getting apps for 13736701241443849285
E/Main    (30189): Error while requesting developer console : com.github.andlyticsproject.console.v2.DevConsoleV2.post(DevConsoleV2.java:409)
E/Main    (30189): com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfos(DevConsoleV2.java:205)
E/Main    (30189): com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfosAndStatistics(DevConsoleV2.java:115)
E/Main    (30189): com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:103)
E/Main    (30189): com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:521)
E/Main    (30189): com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:488)
E/Main    (30189): android.os.AsyncTask$2.call(AsyncTask.java:288)
E/Main    (30189): java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/Main    (30189): java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/Main    (30189): java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/Main    (30189): java.lang.Thread.run(Thread.java:818)
E/Main    (30189): org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:71)
E/Main    (30189): org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:59)
E/Main    (30189): org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:657)
E/Main    (30189): org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:627)
E/Main    (30189): org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:616)
E/Main    (30189): com.github.andlyticsproject.console.v2.DevConsoleV2.post(DevConsoleV2.java:403)
E/Main    (30189): com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfos(DevConsoleV2.java:205)
E/Main    (30189): com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfosAndStatistics(DevConsoleV2.java:115)
E/Main    (30189): com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:103)
E/Main    (30189): com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:521)
E/Main    (30189): com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:488)
E/Main    (30189): android.os.AsyncTask$2.call(AsyncTask.java:288)
E/Main    (30189): java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/Main    (30189): java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/Main    (30189): java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/Main    (30189): java.lang.Thread.run(Thread.java:818)
E/Main    (30189): Error while requesting developer console : Status-Code: 403
E/Main    (30189): com.github.andlyticsproject.console.NetworkException: Status-Code: 403
E/Main    (30189): 	at com.github.andlyticsproject.console.v2.DevConsoleV2.post(DevConsoleV2.java:409)
E/Main    (30189): 	at com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfos(DevConsoleV2.java:205)
E/Main    (30189): 	at com.github.andlyticsproject.console.v2.DevConsoleV2.fetchAppInfosAndStatistics(DevConsoleV2.java:115)
E/Main    (30189): 	at com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:103)
E/Main    (30189): 	at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:521)
E/Main    (30189): 	at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:488)
E/Main    (30189): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
E/Main    (30189): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/Main    (30189): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/Main    (30189): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/Main    (30189): 	at java.lang.Thread.run(Thread.java:818)
E/Main    (30189): Caused by: org.apache.http.client.HttpResponseException: Forbidden
E/Main    (30189): 	at org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:71)
E/Main    (30189): 	at org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:59)
E/Main    (30189): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:657)
E/Main    (30189): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:627)
E/Main    (30189): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:616)
E/Main    (30189): 	at com.github.andlyticsproject.console.v2.DevConsoleV2.post(DevConsoleV2.java:403)
E/Main    (30189): 	... 10 more
````

**Comment by Tedix** [comment]
I have the same problem:

I have problem synchronize my applications. Since 27.10 I'm getting synchronization error in toast.
Under my account I have 5 accounts of my customers.

Thank yoi,

**Comment by xjswxdx** [comment]
good

**Comment by willlunniss** [comment]
Is the app able to fetch stats for any of your linked accounts, maybe you don't have the required permissions for one of them?

**Comment by knirirr** [comment]
@willlunniss your comment reminds me that I am a member of two teams(?), the owners of which have not accepted the new developer agreement and are unlikely to, as I suspect they've forgotten about these accounts.

**Comment by willlunniss** [comment]
OK so if it is a case of one or more linked accounts not having the correct permissions we need to either try to determine if we have access, or continue onto the next account if we get an exception (and store the exception so that we can alert the user that there is a problem with the account).

Can you firstly put a try catch with a continue at https://github.com/AndlyticsProject/andlytics/blob/dev/src/com/github/andlyticsproject/console/v2/DevConsoleV2.java#L205 to confirm its a problem with one of your accounts.

Then have a look to see if there is anything in the initial response that idicates the access issues with the problematic accounts. A good place to start would be https://github.com/AndlyticsProject/andlytics/blob/6967dab5b5f86b83201b64bfd67478bc1326732d/src/com/github/andlyticsproject/console/v2/BaseAuthenticator.java#L161

**Comment by knirirr** [comment]
Trying a catch and continue at the location specified in your first link gives me:

E/DevConsoleV2(  481): Failed to access account for developerId: <id>
E/DevConsoleV2(  481): Error: com.github.andlyticsproject.console.NetworkException: Status-Code: 403   

Since console access is blocked due to the non-acceptance of the new terms that probably explains the 403. I'm now able to access my main account with the debug version of Andlytics I just compiled, so it seems that that was the problem for me.

**Comment by willlunniss** [comment]
OK, please have a look at the response that contains the developer ids that are used to build the session credentials (second link) to see if there is any indication that that an account is not authorised.

**Comment by knirirr** [comment]
I'm not sure if this is what you're after, but an example of the sort of thing I get back from the startup data when session credentials are fetched is this:

"DeveloperConsoleAccounts":"{\"1\":[{\"1\":\"id_here\",\"2\":\"First dodgy account\",\"3\":false},{\"1\":\"id_here\",\"2\":\"Second dodgy account\",\"3\":false},{\"1\":\"id_here\",\"2\":\"Good account\",\"3\":true}]}","PolicyViolationSettings":"{\"1\":[21,22]}"

**Comment by willlunniss** [comment]
OK, So what if you change this https://github.com/AndlyticsProject/andlytics/blob/6967dab5b5f86b83201b64bfd67478bc1326732d/src/com/github/andlyticsproject/console/v2/BaseAuthenticator.java#L63 to the following (syntax not tested)

```
if (accountObj.getBoolean("3")) {
   devAccounts.add(new DeveloperConsoleAccount(developerId, developerName));
} else {
   Log.w(TAG, "[findDeveloperAccounts] Skipping account " + developerId + " for  " + developerName + " because account is not authorised/developer agreament has not been accepted");
}

**Comment by knirirr** [comment]
That change (the syntax was OK) gets the app working again - I removed the "continue" from DevConsoleV2 and was still able to access my account.

**Comment by willlunniss** [comment]
OK great. I'll push a slightly different fix in a bit. Will need to work out a way to report it to the user though other than just writing to the log.

**Comment by knirirr** [comment]
Would a toast suffice? That should be easy to add in, at least as a
short-term solution.

**Comment by willlunniss** [comment]
But it could be for a situation like yours where they will never have access. We don't want to spam them every time we fetch stats.

**Comment by willlunniss** [comment]
Can you test this PR please https://github.com/AndlyticsProject/andlytics/pull/675

**Comment by knirirr** [comment]
That would appear to do the trick, thanks.

**Comment by mathrawka** [comment]
I had a 2nd account from a previous job that didn't accept the terms. Switching accounts and accepting the terms fixed it for me.

**Comment by Tedix** [comment]
Yes there is problem with not accepting the terms from site of my customer. :( Thank you for fix :-)

**Comment by willlunniss** [comment]
OK, so in all cases are you guys able to switch to the other account and accept the terms? In which case, should we prompt the user until they have fixed the problem?

**Comment by knirirr** [comment]
I was not able to accept the terms in the linked accounts, and had to prompt the owners of those accounts to do it. Eventually, they have.

**Comment by peterdk** [comment]
I tested PR #675, it works. It allows me again to download stats from my apps that are still available to access. Could this be merged ?

**Comment by nelenkov** [comment]
See my comments at #675, but this doesn't appear to work anymore, at least for me. The `canUse` flag is always false, even though getting stats works.

**Comment by willlunniss** [comment]
Oh sorry I missed that. Is anyone still experiancing the initial problem?

**Comment by peterdk** [comment]
I am still having issues accessing accounts without this patch, if that is what you mean.

**Comment by willlunniss** [comment]
Can you check the response for your accounts tht work vs those that don't to see if there are any differences?
