### ISSUE TITLE
[future bugg?] ClientLogin deprecated

### ISSUE THREAD

**Issue by iveqy** [AndlyticsProject/andlytics#676]
Hi,
first of all thank you for the execellt documentation and the blog posts about googles login process. I'm in the same situation myself (trying to get my app do to a "offline" access to get the dev_acc from a user).

Reading your code gives me your solution for this and it seems to involve ClientLogin authorization. Digging a bit deeper it seems like this will stop working in april this year. (That's why I post this bug request, to ensure that this won't be a problem for andlytics).

Do you have any plans for this? My attempts to use oauth2 fails, since I fail to require the correct permissions to access the developer console. What's your approach to this?

**Comment by nelenkov** [comment]
The app doesn't use ClientLogin, so this shouldn't be a problem. What coded did you look at?

**Comment by iveqy** [comment]
I'm looking at andlytics/src/com/github/andlyticsproject/console/v2/AccountManagerAuthenticator.java which seems to use the Ubertoken method described in 
http://nelenkov.blogspot.se/2012/11/sso-using-account-manager.html (excellent blog post btw). That blogpost mentions under 1. in "Logging in using AccountManager" that the first step is to get a ClientLogin token.

If it's not a ClientLogin token, what token is it used to pass to IssueAuthToken?

**Comment by nelenkov** [comment]
This post is over 2 years old :) `AccountManagerAuthenticator` is not used any more, have a look at `OauthAccountManagerAuthenticator.java`

**Comment by iveqy** [comment]
Thanks!
