### ISSUE TITLE
Unable to get updates

### ISSUE THREAD

**Issue by alexblack** [AndlyticsProject/andlytics#684]
Hi, just yesterday the app stopped getting updates for me.  Instead it pops up a screen:

"Sorry... Updates are currently not possible, probably because the remote interface changed.  Please help us to fix this by sending us error report data. ..."

I sent in a report.

**Comment by RoadXY** [comment]
Maybe related to this?
https://github.com/AndlyticsProject/andlytics/pull/683

**Comment by willlunniss** [comment]
Duplicate of #683
