### ISSUE TITLE
Material design

### ISSUE THREAD

**Issue by alorma** [AndlyticsProject/andlytics#693]
Hi!

Any plan to update this app to new (1 year) material design?

Did you need help with that?

**Comment by AndyScherzinger** [comment]
Hi @alorma 

none of us had found the time to work on that yet, but if you want to give it a go you are more than welcome! :)

In case you want to get working on it, please fork the repo, base your changes on the dev branch and also send to pull request against the dev branch.

cc: @willlunniss @nelenkov

**Comment by alorma** [comment]
Yes i will try if have time.

If your are agree, i will follow some steps:

* ActionBar -> Toolbar
* BottomBar -> Toolbar
* List to recycler
* GridLayout on tablet (3 columns?)
* more

**Comment by willlunniss** [comment]
As @AndyScherzinger said, we have really been struggling to find the time to work on the app.

I would suggest that you do this in a few stages, firstly move to AppCompat. Then work on the other changes. Moving the account switcher to a navigation draw would bring the app more inline with design guidelines. We may be able to get rid of the bottom bar now, have the progress bar as a horizontal one as part of the ActionBar, and move the actions to the overflow menu.

What is the benifit of converting existing lists to recycler view?

**Comment by alorma** [comment]
The recycler view part is that we can have a Tablet / landscape view
easily. Showing N columns without changing the view type

**Comment by AndyScherzinger** [comment]
Sounds fine to me, especially doing it in an iterative manner. Besides the column argument the Recycler view is also better performance wise since as per my understanding it only renders the items actually visible on the screen :)

One step I am missing atm would be the preference activity since this one might than have to be fixed with the Delegation class of AppCompat to have if running a gain for starters.

We should also maybe think about a FAB since it would be nice to have the primary action(s) on  the screen and not hidden in the overflow menu UX wise

**Comment by nelenkov** [comment]
@alorma If you decide to go through with this, definitely do it step by step. Recycler view should probably be last, after everything else is working.

**Comment by AndyScherzinger** [comment]
I agree with @nelenkov , either first or last since it doesn't have a relation to the necessary toolbar changes. This could even be split into separate pull request which would also make it easier to review (less changes per PR :))

**Comment by alorma** [comment]
Of course i will split it in a different PR.

I will try to make them intependent, so it can be applied alone

**Comment by AndyScherzinger** [comment]
Sounds all good to me! :+1:

**Comment by alorma** [comment]
That is a hard job...

Too much places where old ActionBar is called  :disappointed: 

![DetailScreen](http://imgur.com/qNnhQWN)

**Comment by nelenkov** [comment]
Well, yes, it's a moderately complex application :) As @willlunniss says, you should try to first migrate to AppCompat (there should be at least one outstanding PR that does this to some extent). This will be a big change, but fairly mechanical. Then fix any obvious bugs that surface. Finally, start changing/moving stuff around.

**Comment by willlunniss** [comment]
How is it going?

**Comment by AlexLardschneider** [comment]
Any progress on this?
