### ISSUE TITLE
Fail to  get rating

### ISSUE THREAD

**Issue by zhongzewu** [AndlyticsProject/andlytics#700]
This morning , I can not get my app rating

**Comment by willlunniss** [comment]
Going to need version details and a logcat or PR, cannot do anything with what you have provided....

**Comment by zhongzewu** [comment]
I found there is something wrong with JsonParser.parseRatings, I can not use the code to get any rating。It seems rating interface changing. please check it out!

JsonParser.parseRatings(String json, AppStats stats)
JSONObject values = new JSONObject(json).getJSONObject("result").getJSONArray("1")
				.getJSONObject(0);

		// Ratings are at index 2 - 6
		stats.setRating(values.getInt("2"), values.getInt("3"), values.getInt("4"),
				values.getInt("5"), values.getInt("6"));

Also, I like to know what that  the param ' json' struct from JsonParser.parseRatings(String json, AppStats stats)

**Comment by willlunniss** [comment]
This was fixed in dev and released a few days ago as 2.7.3

**Comment by zhongzewu** [comment]
ok
