### ISSUE TITLE
Replies cannot contain double quotes

### ISSUE THREAD

**Issue by westonized** [AndlyticsProject/andlytics#701]
I tried to reply twice with a message that had quotes in it and got a message about. "Network error" both times, sorry not got exact message, it was a toast. Third time left out quotes worked fine.

Suspect no escaping of quotes is cause.

**Comment by willlunniss** [comment]
Thanks for the report, fancy doing a PR?

**Comment by westonized** [comment]
Sure I'll take a look if I get a moment.
