### ISSUE TITLE
Negative Download Count

### ISSUE THREAD

**Issue by Timoral** [AndlyticsProject/andlytics#712]
I am getting a negative total download count on my app.. This can't be right as downloads don't just reverse themselves..
Unless accounts are being suspended and app downloads go down because of this..

The actual numbers are correct though.

Screenshot:
![screenshot_2015-10-17-15-50-13](https://cloud.githubusercontent.com/assets/9131570/10559376/3e9b5df8-74e7-11e5-980b-943b851f3045.png)

**Comment by willlunniss** [comment]
What does the developer console show?

**Comment by Timoral** [comment]
The console says the same value so those are correct but the counters are negative on total downloads are odd..

**Comment by willlunniss** [comment]
Google quite often adjusts the stats which is why you are seeing negative values.
