### ISSUE TITLE
The earnings number disappeared

### ISSUE THREAD

**Issue by mntgoat** [AndlyticsProject/andlytics#715]
Earlier today the earnings values disappeared and I haven't been able to get them back. I'm guessing something on the site changed.

**Comment by willlunniss** [comment]
Just pushed a fix to master, please test and then we can do a release

**Comment by mntgoat** [comment]
I must have done something wrong because the last commit on my freshly cloned version of andlytics is from Oct 11.

**Comment by willlunniss** [comment]
Sorry, not sure why the PR didn't merge, it's done now. In future you can always merge a PR locally to test though.

**Comment by mntgoat** [comment]
That fixed it.
