### ISSUE TITLE
Does this app work anymore?

### ISSUE THREAD

**Issue by johnmollaghan** [AndlyticsProject/andlytics#720]
I get network error when I try to run this app now.

Does it work for anyone?

**Comment by willlunniss** [comment]
Yes its working fine for me. Please post a logcat showing the actual error.

**Comment by johnmollaghan** [comment]
How can I get a logcat from the app?

Thanks

John

On 30 January 2016 at 09:53, Will Lunniss <notifications@github.com> wrote:

> Yes its working fine for me. Please post a logcat showing the actual error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AndlyticsProject/andlytics/issues/720#issuecomment-177134107>
> .
>



-- 

Moments Videos on Facebook <https://www.facebook.com/MomentsVideosFanPage>

www.momentsvideos.com
021 4381036     087 7991387

**Comment by willlunniss** [comment]
The same way you would for any app (including your own), using adb. Google it if you don't know how.
