### ISSUE TITLE
Authenticaion failed error. Used to work fine

### ISSUE THREAD

**Issue by srujan7** [AndlyticsProject/andlytics#735]
All of a sudden I am gerting authentication failed error for my email address. I reinstalled but no luck. I didnt change anything which might have made this error happen

**Comment by bengtj100** [comment]
It seems that Google removed the login-method Andlytics is using. The app will no longer log me in.

I'm using the same method in a personal script and now it seems that Google redirects my login attempt to the standard login-page.

**Comment by srujan7** [comment]
I hope there will be an alternative afterall. I like this app more than the official google dev console app.

**Comment by willlunniss** [comment]
Please can you post a locat showing the error (remove emails/authtokens)?

**Comment by srujan7** [comment]
---- Sep 2, 2016 12:59:21 PM ----

09-02 12:53:25.603 22964 23759 E         : netstack:  STAT_HUB - App com.github.andlyticsproject isn't supported

09-02 12:58:55.725 27372 27392 E Main    : Error while requesting developer console : com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticateInternal(OauthAccountManagerAuthenticator.java:167)

09-02 12:58:55.725 27372 27392 E Main    : com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticate(OauthAccountManagerAuthenticator.java:71)

09-02 12:58:55.725 27372 27392 E Main    : com.github.andlyticsproject.console.v2.DevConsoleV2.authenticate(DevConsoleV2.java:349)

09-02 12:58:55.725 27372 27392 E Main    : com.github.andlyticsproject.console.v2.DevConsoleV2.authenticateFromScratch(DevConsoleV2.java:328)

09-02 12:58:55.725 27372 27392 E Main    : com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:103)

09-02 12:58:55.725 27372 27392 E Main    : com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:521)

09-02 12:58:55.725 27372 27392 E Main    : com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:488)

09-02 12:58:55.735 27372 27392 E Main    : com.github.andlyticsproject.console.AuthenticationException: Cannot get uber token. Got: Error=badauth

09-02 12:58:55.735 27372 27392 E Main    : 	at com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticateInternal(OauthAccountManagerAuthenticator.java:167)

09-02 12:58:55.735 27372 27392 E Main    : 	at com.github.andlyticsproject.console.v2.OauthAccountManagerAuthenticator.authenticate(OauthAccountManagerAuthenticator.java:71)

09-02 12:58:55.735 27372 27392 E Main    : 	at com.github.andlyticsproject.console.v2.DevConsoleV2.authenticate(DevConsoleV2.java:349)

09-02 12:58:55.735 27372 27392 E Main    : 	at com.github.andlyticsproject.console.v2.DevConsoleV2.authenticateFromScratch(DevConsoleV2.java:328)

09-02 12:58:55.735 27372 27392 E Main    : 	at com.github.andlyticsproject.console.v2.DevConsoleV2.getAppInfo(DevConsoleV2.java:103)

09-02 12:58:55.735 27372 27392 E Main    : 	at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:521)

09-02 12:58:55.735 27372 27392 E Main    : 	at com.github.andlyticsproject.Main$LoadRemoteEntries.doInBackground(Main.java:488)

---- Sep 2, 2016 12:59:21 PM ----

**Comment by srujan7** [comment]
@willlunniss any updates? Is this app working for everybody else?

**Comment by willlunniss** [comment]
Working here for me. I'll try to have a look tonight. Was there anything else in the log? What happens if you try to sign in through your browser?

**Comment by srujan7** [comment]
Well well, I tried all but nothing worked. Finally I went to my phone settings and removed all gmail accounts from there. Went to andlytics -> add account  and addded my gmail dev account. Working now.

**Comment by willlunniss** [comment]
OK, glad it is working now.
