### ISSUE TITLE
No published apps found

### ISSUE THREAD

**Issue by caarmen** [AndlyticsProject/andlytics#745]
I was checking my google account security settings: https://myaccount.google.com/permissions

I noticed that Andlytics had "full access to your Google Account", which is more than any other app has (except Chrome).

I thought (hoped) that perhaps Andlytics may have needed this in the past, but has since made improvements to only request minimum permissions to access Play Store app data.

So, I removed this access in the security settings.

Then I uninstalled Andlytics from my phone and reinstalled it from the Play Store.

I opened Andlytics and selected my Google account: the only one on my phone, and the same one I was using before.  It's not a "Google Apps for Business" account, and not linked to multiple developer consoles.

It displays no apps, and says "No published apps found".

Any clue how I can get this working again?  I saw one other issue (https://github.com/AndlyticsProject/andlytics/issues/735)  where somebody had to remove and re-add their Google account on the phone, but I'm hoping I don't have to do that.

**Comment by caarmen** [comment]
For info, I have enabled 2-step authentication on my Google account, in case that's relevant.

**Comment by caarmen** [comment]
Update: I just saw a notification on my phone, leading to a popup, where Andlytics is now asking for full account access again.  I guess if I say "Allow" it will continue to work as before.

So I guess I have two questions:
1) What action triggers this access request?  I didn't see any way to force it.  I was stuck with "No published apps found" for a while, then later, without my intervention, I saw this notification/popup.
2) Does Andlytics really need **full** access?  Isn't there some subset of permissions that could be sufficient to read app stats?

Thanks!

**Comment by nelenkov** [comment]
The notification is triggered by background sync.

Andlytics uses an unofficial API to get a master token, which is then exchanged for an authentication cookie.
There is no easy way around that without reimplementing major parts of the app.

If you are worried about permissions, use the official Google app.

**Comment by caarmen** [comment]
Ok, thanks for the explanations.
